config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  devise_for :users

  resources :offenders do
    collection do
      get :modal_index
      get :generate_pdf
      get :generate_sheet
    end
  end

  resources :dashboard

  resources :analysis, only: [:update] do
    collection do
      get :unconformities, as: :unconformities
      get :simulator, as: :simulator
      get :load_simulator_modal, :load_simulator_modal
      get :update_table
      get :reload_simulation
    end
  end

  resources :simulations do
    collection do
      post :new_simulation
    end
  end

  resources :indicators, only: [] do
    collection do
      get :indicator_01, as: :indicator_01
      get :units, as: :units
      get :unit_profile
    end
  end

  resources :maps, only: [:index] do
  end

  resources :roles
  resources :users
  resources :units, only: [:index, :edit, :update, :show]

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "home#index"
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
  before_action :authenticate_user!
  skip_after_action :verify_policy_scoped
  skip_after_action :verify_authorized

  def unconformities
    @units = Unit.all
    @is_simulator = false
  end

  def simulator
    @units = Unit.all
    @is_simulator = true
  end

  def load_simulator_modal
    @origin_unit = params[:origin_unit].to_i
    @units = Unit.where.not(id: @origin_unit)
    @age = params[:age].to_i
    @measure_type = params[:measure_type]
    @unit_measure = params[:unit_measure]

    if params[:extra]
      @current_value = params[:extra].to_i
    else
      @current_value = params[:offenders_amount].to_i
    end
    respond_with(@units, layout: false)
  end

  def reload_simulation
    @simulation = Simulation.find(params[:id])
  end

  def update_table
    @origin_unit = Unit.find(params["/analysis/update_table"][:origin_unit])
    @unit = Unit.find(params["/analysis/update_table"][:unit])
    @age = params["/analysis/update_table"][:age]
    @measure_type = params["/analysis/update_table"][:measure_type]
    @unit_measure = params["/analysis/update_table"][:unit_measure]
    @to_update = params["/analysis/update_table"][:current_value].to_i
    @old_value = params["/analysis/update_table"][:old_value].to_i
    @target_cell_value = params[:target_cell_value].to_i
    @origin_occupation = params[:origin_occupation].to_i - @to_update
    @target_occupation = params[:target_occupation].to_i + @to_update
    @text_simulator_in = I18n.t("views.analysis.simulator_movements_in", value: @to_update,
                              origin: @origin_unit.name, age: @age, measure: @measure_type)
    @text_simulator_out = I18n.t("views.analysis.simulator_movements_out", value: @to_update,
                                target: @unit.name, age: @age, measure: @measure_type)
  end

end

app/helpers/analysis_helper.rb
module AnalysisHelper
  def show_inconsistences(unit_id, inconsistences_value)
    td_class = ""
    if inconsistences_value > 0
      td_class = "table-light-blue-rowspan text-center"
    end

    content_tag(:td, class: td_class) do
      if inconsistences_value > 0
        link_to "#", class: "index-object link-index-black", data: { link: modal_index_offenders_path(unit_id: unit_id ) } do
          concat(inconsistences_value)
        end
      end
    end
  end

  def show_table_unconformities_value(age_value, min_age, max_age, measure_value, unit_id, measure_type, unit_measure, is_simulator)
    td_class = ""

    link = is_simulator ? load_simulator_modal_analysis_index_path(offenders_amount: measure_value, origin_unit: unit_id, age: age_value, measure_type: truncate_words(measure_type), unit_measure: unit_measure) : modal_index_offenders_path(q:
            { age_eq: age_value, unit_id_eq: unit_id, measures_measure_type_in: measure_type})

    unit = Unit.find(unit_id)
    unit_measures = unit.measure_type_names

    if measure_value > 0
      if age_value.between?(min_age, max_age) && (unit_measures.include?(unit_measure))
        td_class = "table-blue-rowspan text-center"
      elsif unit.measure_types.map(&:name).include?(unit_measure)
        td_class = "table-yellow-rowspan text-center"
      elsif age_value.between?(min_age, max_age)
        td_class = "table-red-rowspan text-center"
      else
        td_class = "table-orange-rowspan text-center"
      end
    end

    content_tag(:td, class: td_class, id: "#{unit_id}-#{truncate_words(measure_type)}-#{age_value}") do
      if measure_value > 0
        link_to "#", class: "index-object btn-edit-object link-index-black", data: { link: link } do
          concat(content_tag(:span, measure_value))
        end
      end
    end

  end
end

app/views/analysis/_table_unconformities.html.erb
<div class="container overflow-visible">
  <div class="tile">
    <table class="table">
      <tbody>
        <tr>
          <td>
              <button type="button" class="btn m-r-sm btn-total-measure">
                <span id="total-measure-span"><span>
              </button>
              <%= t("views.analysis.total_on_measure") %>
          </td>
          <td>
              <button type="button" class="btn m-r-sm btn-total-age">
                <span id="total-age-span"><span>

              </button>
              <%= t("views.analysis.total_on_age") %>
          </td>
          <td>
             <button type="button" class="btn m-r-sm btn-total-age-measure">
               <span id="total-age-measure-span"><span>

             </button>
             <%= t("views.analysis.total_on_measure_age") %>
          </td>
          <td>
             <button type="button" class="btn m-r-sm total-conformities">
               <span id="total-conformities-span"><span>
             </button>
             <%= t("views.analysis.total_conformities") %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

</div>

<div class="container overflow-visible">
  <div class="tile">
    <div class="table-responsive">

    <table id="unconformities-table" class="table analysis-table">
      <thead>
        <tr>
          <th rowspan="3" class="table-strong-green-rowspan"><%= t("views.analysis.unit") %></th>
          <% if @is_simulator %>
            <th rowspan="3" class="table-strong-green-rowspan minimum-width-tr"><%= t("views.analysis.age_group") %></th>
            <th rowspan="3" class="table-strong-green-rowspan minimum-width-tr"><%= t("views.analysis.occupation") %></th>
            <th rowspan="3" class="table-strong-green-rowspan minimum-width-tr"><%= t("views.analysis.out_off_profile_percentage") %></th>
          <% end %>

          <th colspan="9" class="table-strong-green-rowspan"><%= t("views.analysis.provisory") %></th>
          <th colspan="9" class="table-strong-green-rowspan"><%= t("views.analysis.detention") %></th>
          <th colspan="9" class="table-strong-green-rowspan"><%= t("views.analysis.penalty") %></th>
          <th rowspan="3" class="table-light-blue-rowspan vertical-text"><span><%= t("views.analysis.inconsistences") %></span></th>

        </tr1>

        <tr>
          <th colspan="9" class="table-light-green-rowspan"><%= t("views.analysis.age_group") %></th>
          <th colspan="9" class="table-light-green-rowspan"><%= t("views.analysis.age_group") %></th>
          <th colspan="9" class="table-light-green-rowspan"><%= t("views.analysis.age_group") %></th>
        </tr>

        <tr>
          <th class="table-light-green-rowspan text-center age-th">12</th>
          <th class="table-light-green-rowspan text-center age-th">13</th>
          <th class="table-light-green-rowspan text-center age-th">14</th>
          <th class="table-light-green-rowspan text-center age-th">15</th>
          <th class="table-light-green-rowspan text-center age-th">16</th>
          <th class="table-light-green-rowspan text-center age-th">17</th>
          <th class="table-light-green-rowspan text-center age-th">18</th>
          <th class="table-light-green-rowspan text-center age-th">19</th>
          <th class="table-light-green-rowspan text-center age-th">20</th>

          <th class="table-light-green-rowspan text-center age-th">12</th>
          <th class="table-light-green-rowspan text-center age-th">13</th>
          <th class="table-light-green-rowspan text-center age-th">14</th>
          <th class="table-light-green-rowspan text-center age-th">15</th>
          <th class="table-light-green-rowspan text-center age-th">16</th>
          <th class="table-light-green-rowspan text-center age-th">17</th>
          <th class="table-light-green-rowspan text-center age-th">18</th>
          <th class="table-light-green-rowspan text-center age-th">19</th>
          <th class="table-light-green-rowspan text-center age-th">20</th>

          <th class="table-light-green-rowspan text-center age-th">12</th>
          <th class="table-light-green-rowspan text-center age-th">13</th>
          <th class="table-light-green-rowspan text-center age-th">14</th>
          <th class="table-light-green-rowspan text-center age-th">15</th>
          <th class="table-light-green-rowspan text-center age-th">16</th>
          <th class="table-light-green-rowspan text-center age-th">17</th>
          <th class="table-light-green-rowspan text-center age-th">18</th>
          <th class="table-light-green-rowspan text-center age-th">19</th>
          <th class="table-light-green-rowspan text-center age-th">20</th>
        </tr>
      </thead>
      <tbody>
        <% @units.each do |unit| %>
        <tr id='unit-<%= unit.id %>'>
          <span hidden id="unit-capacity-<%= unit.id %>">
            <%= unit.capacity %>
          </span>
          <% if !@is_simulator %>
            <td>
              <div class="text-left" data-trigger="hover" data-html="true" data-toggle="popover" data-placement="right" data-content="<%= simple_format(t('views.analysis.unit_information', min_age: unit.min_age, max_age: unit.max_age, occupation: unit.occupied, offenders_out_of_profile: unit.offenders_out_of_profile_by_age, measures: unit.measure_type_names, out_of_profile_percentage: unit.offenders_out_of_profile_percentage))%>" title="<%= unit.name %>" data-original-title="">
                <%= truncate_words unit.name %>
              </div>
            </td>
          <% else %>
            <td>
              <%= truncate_words unit.name %>
            </td>
            <td class="text-center">
              <%= "#{ unit.min_age }-#{ unit.max_age }" %>
            </td>
            <td class="text-center" id="unit-occupation-<%= unit.id %>">
              <%= unit.occupied %>
            </td>
            <td class="text-center" id="unit-out-of-profile-<%= unit.id %>">
              <%= unit.offenders_out_of_profile_percentage %>%
            </td>
          <% end %>

          <%= show_table_unconformities_value(12, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(12, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>
          <%= show_table_unconformities_value(13, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(13, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>
          <%= show_table_unconformities_value(14, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(14, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>
          <%= show_table_unconformities_value(15, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(15, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>
          <%= show_table_unconformities_value(16, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(16, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>
          <%= show_table_unconformities_value(17, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(17, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>
          <%= show_table_unconformities_value(18, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(18, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>
          <%= show_table_unconformities_value(19, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(19, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>
          <%= show_table_unconformities_value(20, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(20, "Internação Provisória"), unit.id, "Internação Provisória", "Unidade de Internação Provisória", @is_simulator) %>

          <%= show_table_unconformities_value(12, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(12, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>
          <%= show_table_unconformities_value(13, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(13, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>
          <%= show_table_unconformities_value(14, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(14, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>
          <%= show_table_unconformities_value(15, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(15, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>
          <%= show_table_unconformities_value(16, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(16, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>
          <%= show_table_unconformities_value(17, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(17, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>
          <%= show_table_unconformities_value(18, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(18, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>
          <%= show_table_unconformities_value(19, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(19, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>
          <%= show_table_unconformities_value(20, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(20, "Internação"), unit.id, "Internação","Unidade de Internação", @is_simulator) %>

          <%= show_table_unconformities_value(12, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(12, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>
          <%= show_table_unconformities_value(13, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(13, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>
          <%= show_table_unconformities_value(14, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(14, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>
          <%= show_table_unconformities_value(15, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(15, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>
          <%= show_table_unconformities_value(16, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(16, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>
          <%= show_table_unconformities_value(17, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(17, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>
          <%= show_table_unconformities_value(18, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(18, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>
          <%= show_table_unconformities_value(19, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(19, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>
          <%= show_table_unconformities_value(20, unit.min_age, unit.max_age, unit.count_applied_measure_by_age(20, "Sanção"), unit.id, "Sanção", "Unidade de Sanção", @is_simulator) %>

          <%= show_inconsistences(unit.id, unit.inconsistences) %>

        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  </div>
</div>
<%= render partial: "layouts/skinny_modal" %>

app/views/analysis/_update_row.html.erb
<%= show_table_unconformities_value(age, unit.min_age, unit.max_age, value, unit.id, measure_type, unit_measure, true) %>

app/views/analysis/load_simulator_modal.html.erb
<span class="content-modal">
  <div class="modal-body">

  <%= simple_form_for update_table_analysis_index_path do |f| %>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= f.input :current_value, collection: 1..@current_value, label: t("views.analysis.offenders_amount"),
                input_html: { class: "" }, include_blank: false %>
          <%= f.input :origin_unit, as: :hidden, input_html: { value: @origin_unit } %>
          <%= f.input :age, as: :hidden, input_html: { value: @age } %>
          <%= f.input :measure_type, as: :hidden, input_html: { value: @measure_type } %>
          <%= f.input :unit_measure, as: :hidden, input_html: { value: @unit_measure } %>
          <%= f.input :old_value, as: :hidden, input_html: { value: @current_value } %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= f.input :unit, collection: @units, label: t("views.analysis.target_unit"),
                input_html: { class: "" }, include_blank: false %>
        </div>
      </div>
    </div>

  <% end %>
  </div>

  <%= render partial: "shared/modal_footer", locals: { submit_id: "btn-submit-update-table" } %>
</span>

app/views/analysis/reload_simulation.js.erb
$('#unconformities-table').html("<%= escape_javascript @simulation.data.html_safe %> ");

$("#simulator-movements").text("<%=escape_javascript @simulation.div_text.to_s %>")

loadModalForm();
countOffenders();

app/views/analysis/simulator.html.erb
<%= render 'table_unconformities' %>

<div class="container overflow-visible">
  <div class="tile">
    <textarea class="simulator-movements" id="simulator-movements" disabled></textarea>
  </div>

  <div class="form-group">
    <button id="load-simulation" class="btn btn-success index-object" data-link="<%= simulations_path %>">
      <%= fa_icon("refresh") %>
      <%=t("views.analysis.load_simulation")%>
    </button>

    <button id="save-simulation" class="btn btn-success" data-link="<%= new_simulation_simulations_path %>">
      <%= fa_icon("save") %>
      <%=t("views.analysis.save")%>
    </button>

    <button id="export-simulator-movements" class="btn btn-success pull-right">
      <%= fa_icon("file-pdf-o") %>
      <%=t("views.analysis.export")%>
    </button>
  </div>

</div>

app/views/analysis/unconformities.html.erb
<%= render 'table_unconformities' %>

app/views/analysis/update_table.js.erb
$('#<%= @origin_unit.id %>-<%= @measure_type %>-<%= @age %>').replaceWith("<%= escape_javascript(render partial: 'update_row', locals: { unit: @origin_unit, age: @age.to_i, measure_type: @measure_type, unit_measure: @unit_measure, value: @old_value - @to_update } ) %>");

$('#<%= @unit.id %>-<%= @measure_type %>-<%= @age %>').replaceWith("<%= escape_javascript(render partial: 'update_row', locals: { unit: @unit, age: @age.to_i, measure_type: @measure_type, unit_measure: @unit_measure, value: @target_cell_value + @to_update} ) %>");


var occupation = parseInt($('#unit-occupation-<%= @unit.id %>').html())

$('#unit-occupation-<%= @origin_unit.id %>').html('<%= @origin_occupation %>')
$('#unit-occupation-<%= @unit.id %>').html('<%= @target_occupation %>')

loadModalForm();
countOffenders();
countOutOfProfile('<%= @unit.id %>');
countOutOfProfile('<%= @origin_unit.id %>');

$("#simulator-movements").text(
  $('#simulator-movements').text()+ '\n' + '<%= @unit.name %>:\n' + '<%= @text_simulator_in %>' + '\n' +
  '<%= @origin_unit.name %>:\n' + '<%= @text_simulator_out %>' + '\n' )