config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  devise_for :users

  resources :offenders do
    collection do
      get :modal_index
      get :generate_pdf
      get :generate_sheet
    end
  end

  resources :dashboard

  resources :analysis, only: [:update] do
    collection do
      get :unconformities, as: :unconformities
      get :simulator, as: :simulator
      get :load_simulator_modal, :load_simulator_modal
      get :update_table
      get :reload_simulation
    end
  end

  resources :simulations do
    collection do
      post :new_simulation
    end
  end

  resources :indicators, only: [] do
    collection do
      get :indicator_01, as: :indicator_01
      get :units, as: :units
      get :unit_profile
    end
  end

  resources :maps, only: [:index] do
  end

  resources :roles
  resources :users
  resources :units, only: [:index, :edit, :update, :show]

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "home#index"
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!
  skip_after_action :verify_policy_scoped
  include Concerns::OffendersControllerConcern
  before_action :set_dependencies, only: [:index]

  def index
    map_configs
    set_unit_markers

    @q = Offender.ransack()
    gon.heatmap_json = []
    gon.district_json = Gmaps4rails.build_markers(District.all) do |d, marker|
      offenders = d.offenders.ransack(params[:q]).result
      if offenders.count > 0
        marker.json({:id => d.name,
                    custom_marker: "<div class='marker-info'>
                                      <img src=#{ActionController::Base.helpers.asset_path('offenders_icon.png')}>
                                      <span>#{offenders.count}</span>
                                      </div>"})
        marker.lat d.latitude
        marker.lng d.longitude

        marker.infowindow render_to_string(:partial => "/offenders/infowindow", :locals => { offenders: offenders })

        offenders.count.times do
          gon.heatmap_json << { lat: d.latitude, lng: d.longitude }
        end
      end
    end

    gon.district_json = gon.district_json.reject { |c| c.empty? }

    respond_to do |format|
      format.html
      format.json { render json: { districts: gon.district_json, heatmap: gon.heatmap_json} }
    end

  end

  private

  def set_unit_markers
    gon.hash_json = Gmaps4rails.build_markers(Unit.all) do |unit, marker|
      marker.lat unit.latitude
      marker.lng unit.longitude
      marker.json({:id => unit.id,
                    custom_marker: "<div class='marker-info'>
                                      <img src=#{ActionController::Base.helpers.asset_path("institution-map.png")}>
                                    </div>"})

      marker.infowindow render_to_string(:partial => "/units/infowindow", :locals => { unit: unit})
    end
  end

  def map_offender_search
  end

  def map_configs
    gon.center_lat = -5.4546
    gon.center_lng = -39.7177
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_search.html.erb
<%= link_to "#", class: "btn btn-success open-search" do %>
  <%= fa_icon("filter")%> <%= t("app.filter") %>
<% end %>

<%= link_to root_path, class: "logo-socioboard" do %>
  <%= image_tag "socioboard-logo.png", width: "100px" %>
<% end %>

<div class="loading-map-data text-center">
  <div class="loading-map-content">
    <%= fa_icon("circle-o-notch spin") %>
    <div class="">
      <%= t("app.please_wait") %>
    </div>
  </div>
</div>

<div class="map-search row">

  <div class="col-md-12 text-right interactive-header">
    <span class="close-search">
      <%= fa_icon "times-circle-o" %>
    </span>
  </div>

  <%= search_form_for @q, url: maps_path do |f| %>
    <div class="row">
      <div class="col-md-12 text-center p-t-20">
        <span>
          <%= link_to "#", id: "search-on-map", class: "btn btn-success btn-icon" do %>
            <%= fa_icon("search") %>
          <% end %>
        </span>
        <span class="m-l-10">
          <%= link_to "#", id: "clear-search", class: "btn bg-gray btn-icon" do %>
            <%= fa_icon("close") %>
          <% end %>
        </span>
        <hr>
      </div>
    </div>
    <div class="form-components">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :id, t('views.maps.unit') %>
          <%= f.select(:unit_id_in, grouped_options_for_select(@units), { include_blank: false }, { class: "select2 form-control medium-select2", multiple: "multiple", data: { value: value_selected("q", "unit_id_in") } }) %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :origin_county_in, t('views.maps.origin_county') %>
          <%= f.select(:origin_county_in, @origin_counties, { include_blank: false }, { class: "select2 form-control medium-select2", multiple: "multiple" }) %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :crimes_name_in, t('views.maps.crimes_name') %>
          <%= f.collection_select(:crimes_name_in, @crimes, :name, :name, { include_blank: false }, { class: "select2 form-control medium-select2", multiple: "multiple" }) %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :measures_measure_type_in, t('views.maps.measure_type') %>
          <%= f.select(:measures_measure_type_in, @measure_types, { include_blank: false }, { class: "select2 form-control medium-select2", multiple: "multiple" }) %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :age_in, t('views.maps.age') %>
          <%= f.collection_select(:age_in, @ages, :age, :age, { include_blank: false }, { class: "select2 form-control medium-select2", multiple: "multiple" }) %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :recurrent_in, t('views.maps.recurrent') %>
          <%= f.collection_select(:recurrent_in, @recurrents, :recurrent, :recurrent, { include_blank: false }, { class: "select2 form-control medium-select2", multiple: "multiple" }) %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :measures_measure_situation_in, t('views.maps.measure_situation') %>
          <%= f.select(:measures_measure_situation_in, @measure_situations, { include_blank: false }, { class: "select2 form-control medium-select2", multiple: "multiple" }) %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :has_biometry_eq, t('views.maps.has_biometry') %>
          <%= f.select :has_biometry_eq, @yes_or_no, { include_blank: true },{ class: "select2 form-control medium-select2" } %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :has_photo_eq, t('views.maps.has_photo') %>
          <%= f.select :has_photo_eq, @yes_or_no, { include_blank: true }, { class: "select2 form-control medium-select2" } %>
        </div>
      </div>

      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :measures_measure_deadline_in, t('views.maps.measure_deadline') %>
          <%= f.select(:measures_measure_deadline_in, @measure_deadlines, { include_blank: false }, { class: "select2 form-control medium-select2", multiple: "multiple" }) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/maps/index.html.erb
<%= render partial: "search" %>

<div id="row">
  <div class="col-md-12 text-center">
    <div id="map">
    </div>
  </div>
</div>