config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  devise_for :users

  resources :offenders do
    collection do
      get :modal_index
      get :generate_pdf
      get :generate_sheet
    end
  end

  resources :dashboard

  resources :analysis, only: [:update] do
    collection do
      get :unconformities, as: :unconformities
      get :simulator, as: :simulator
      get :load_simulator_modal, :load_simulator_modal
      get :update_table
      get :reload_simulation
    end
  end

  resources :simulations do
    collection do
      post :new_simulation
    end
  end

  resources :indicators, only: [] do
    collection do
      get :indicator_01, as: :indicator_01
      get :units, as: :units
      get :unit_profile
    end
  end

  resources :maps, only: [:index] do
  end

  resources :roles
  resources :users
  resources :units, only: [:index, :edit, :update, :show]

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable, :timeoutable

  has_and_belongs_to_many :roles
  has_many :simulations

  def admin?
    act_as?("admin:admin")
  end

  private

  def act_as?(role)
    self.roles.select(:activities).distinct.map(&:activities).flatten.include?(role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = policy_scope(User).page(params[:page])
    respond_with(@users)
  end

  def new
    @user = User.new
    authorize @user
    respond_with(@user)
  end

  def create
    @user = User.new(user_params)
    authorize @user
    @user.save
    respond_with(@user)
  end

  def show
    authorize @user
    respond_with(@user)
  end

  def edit
    authorize @user
    respond_with(@user)
  end

  def update
    authorize @user
    @user.update(user_params)
    respond_with(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :password,
      :email,
      role_ids: []
    )
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <%= f.input :email, label: t('activerecord.attributes.user.email') %>
      </div>
    </div>

    <div class="row-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= f.association :roles %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= f.input :password, label: t('devise.sessions.new_password') %>
      </div>
    </div>

    <div class="row form-actions">
      <hr>
      <div class="col-md-12">
        <%= footer_actions(users_path) %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="tile">
  <div class="t-header">
    <h4><%=t("views.users.edit_user")%></h4>
  </div>
  <div class="t-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container overflow-visible">
  <div class="tile">
    <div class="t-header th-alt bg-teal">
      <div class="th-title">
        <span class="tile-text"><%= t("views.users.list_users")%></span>
      </div>
    </div>

    <table class="table table-stripped">
      <thead>
        <tr>
          <th><%= t("activerecord.attributes.user.email") %></th>
          <th><%= t("activerecord.attributes.user.roles") %></th>
          <th><%= t("activerecord.attributes.user.created_at") %></th>
          <th><%= t("activerecord.attributes.user.updated_at") %></th>
          <th><%= t("views.general.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.email, user_path(user) %></td>
          <td><%= user.roles.map(&:name) %></td>
          <td><%= user.created_at %></td>
          <td><%= user.updated_at %></td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-success dropdown-toggle"  data-toggle="dropdown" aria-expanded="false">
                <%= fa_icon("ellipsis-h") %>
              </button>
              <ul class="dropdown-menu dropdown-menu-right" data-placement="left" role="menu">
                <li>
                  <%= link_to t("link.edit"), edit_user_path(user) %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="tile">
  <div class="t-header">
    <h4><%=t("views.users.new_user")%></h4>
  </div>
  <div class="t-body">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<span class="content-modal">
  <div class="modal-body">
    <table class="table table-stripped">
      <thead class="bg-teal">
        <tr>
          <th colspan="4" class="text-center"><%= @user.email %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <b><%= t("activerecord.attributes.user.roles") %>:</b>
          </td>
          <td>
            <%= @user.roles.map(&:name) %>
          </td>
        </tr>

        <tr>
          <td>
            <b><%= t("activerecord.attributes.user.email") %>:</b>
          </td>
          <td><%= @user.email %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="modal-footer">
    <hr>
    <%= link_to users_path, class: "btn bg-gray btn-icon btn-back", id: "btn-close-modal", data: { dismiss: "modal" } do %>
      <%= fa_icon("mail-reply") %>
    <% end %>
  </div>
</span>