config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  devise_for :users

  resources :offenders do
    collection do
      get :modal_index
      get :generate_pdf
      get :generate_sheet
    end
  end

  resources :dashboard

  resources :analysis, only: [:update] do
    collection do
      get :unconformities, as: :unconformities
      get :simulator, as: :simulator
      get :load_simulator_modal, :load_simulator_modal
      get :update_table
      get :reload_simulation
    end
  end

  resources :simulations do
    collection do
      post :new_simulation
    end
  end

  resources :indicators, only: [] do
    collection do
      get :indicator_01, as: :indicator_01
      get :units, as: :units
      get :unit_profile
    end
  end

  resources :maps, only: [:index] do
  end

  resources :roles
  resources :users
  resources :units, only: [:index, :edit, :update, :show]

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root "home#index"
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :offenders
  has_many :unit_occupations
  has_and_belongs_to_many :measure_types
  mount_uploader :photo, PhotoUploader

  geocoded_by :full_address

  validates :min_age, presence: true, numericality: { greater_than_or_equal_to: 12,
                                                      less_than_or_equal_to: 22 }
  validates :max_age, presence: true, numericality: { greater_than_or_equal_to: 12,
                                                      less_than_or_equal_to: 22 }

  validate  :check_ages

  def full_address
    "#{ street }, #{ county }"
  end

  def measure_types_names
    measure_types.map(&:name).join(", ")
  end

  def occupation_increased?(date)
    old_occupation = unit_occupations.where(day: date).first
    if old_occupation
      if offenders.not_evaded.count > old_occupation.occupation
        return true
      end
    else
      return true
    end

    return false
  end

  def occupation_variation(date)
    old_occupation = unit_occupations.where(day: date).first
    if old_occupation
      return offenders.not_evaded.count - old_occupation.occupation
    else
      return offenders.not_evaded.count
    end
  end

  def occupation_variation_percentage(date)
    total_offenders = offenders.not_evaded.count
    if total_offenders > 0
      (occupation_variation(date).to_f/total_offenders.to_f)*100
    else
      0
    end
  end

  def biggest_occupation
    unit_occupations.maximum("occupation")
  end

  def lowest_occupation
    unit_occupations.minimum("occupation")
  end

  def measure_type_names
    measure_types.map(&:name).join(",")
  end

  def offenders_out_of_profile_by_age
    offenders.not_evaded.where("age < ? OR age > ?", min_age, max_age).count
  end

  def inconsistences
    offenders.not_evaded.where("age < ? OR age > ?", 12, 20).count
  end

  def offenders_out_of_profile
    offenders_out_of_profile_by_age + offenders_out_of_measure
  end

  def offenders_out_of_profile_percentage
    ((offenders_out_of_profile.to_f/capacity.to_f)*(100)).round(2)
  end

  def count_applied_measure_by_age(age, measure_type)
    offenders.not_evaded.where(age: age).joins(:measures).where("measures.measure_type" => measure_type).count
  end

  def offenders_out_of_measure
    count = 0
    if !measure_type_names.include? 'Unidade de Internação'
      count += self.offenders.not_evaded.joins(:measures).where('measure_type = ?', 'Internação').count
    end

    if !measure_type_names.include? 'Unidade de semiliberdade'
      count += self.offenders.not_evaded.joins(:measures).where('measure_type = ?', 'SemiLiberdade').count
    end

    if !measure_type_names.include? 'Unidade de Internação Provisória'
      count += self.offenders.not_evaded.joins(:measures).where('measure_type = ?', 'Internação Provisória').count
    end
    if !measure_type_names.include? 'Unidade de Sanção'
      count += self.offenders.not_evaded.joins(:measures).where('measure_type = ?', 'Sanção').count
    end

    return count
  end

  def analysis_data_count
    ages_range = (12..20)
    total_conformities       = 0
    total_out_of_age         = 0
    total_out_of_measure     = 0
    total_age_and_measure    = 0
    ages_range.each do |age|
      measures = [ { measure: I18n.t("activerecord.attributes.offender.measure_type_list.provisional_admission"), unit_measure: "Unidade de Internação Provisória" },
                   { measure: I18n.t("activerecord.attributes.offender.measure_type_list.admission"), unit_measure: "Unidade de Internação"},
                   { measure: I18n.t("activerecord.attributes.offender.measure_type_list.sanction"), unit_measure: "Unidade de Sanção"} ]

      measures.each do |measure|
        if age.between?(min_age, max_age) && measure_type_names.include?(measure[:unit_measure])
          total_conformities += self.count_applied_measure_by_age(age, measure[:measure])
        elsif self.measure_types.map(&:name).include?(measure[:unit_measure])
          total_out_of_age += self.count_applied_measure_by_age(age, measure[:measure])
        elsif age.between?(min_age, max_age)
          total_out_of_measure += self.count_applied_measure_by_age(age, measure[:measure])
        else
          total_age_and_measure += self.count_applied_measure_by_age(age, measure[:measure])
        end
      end
    end
    [ total_out_of_measure, total_out_of_age, total_age_and_measure, total_conformities ]
  end

  private

  def check_ages
    if max_age < min_age
      error_string = I18n.t("activerecord.errors.models.attributes.unit.min_age_bigger_than_max")
      errors.add(:max_age, error_string)
    end
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  def index
    @units = policy_scope(Unit.order(:id)).page(params[:page])
    respond_with(@units)
  end

  def show
    authorize @unit
    respond_with(@unit, layout: false)
  end

  def edit
    authorize @unit
    respond_with(@unit)
  end

  def update
    authorize @unit
    if @unit.street == params[:unit][:street]
      @unit.update(unit_params)
    else
      @unit.update(unit_params)
      @unit.geocode
    end
    respond_with(@unit, location: -> { units_path })
  end

  private

  def respond_activity(object, issue_id, status)
  end

  def set_unit
    @unit = Unit.find(params[:id])
  end

  def unit_params
    params.require(:unit).permit(
      :min_age,
      :max_age,
      :street,
      :county,
      :district,
      :photo,
      :photo_cache,
      :latitude,
      :longitude,
      measure_type_ids: []
    )
  end
end

app/helpers/unit_helper.rb
module UnitHelper
  def age_range(min, max)
    return "#{min} - #{max}"
  end

  def initials_measure_unit_type(type)
    unless type.blank?
      initials = []
      type.each do |tu|
        case tu
        when I18n.t("measure_units_types.free_range_unit")
          initials << t("views.indicators.units.free_range_unit_initial")
        when I18n.t("measure_units_types.admission_unit")
          initials << t("views.indicators.units.admission_unit_initial")
        when I18n.t("measure_units_types.provisional_admission_unit")
          initials << t("views.indicators.units.provisional_admission_unit_initial")
        end
      end

      initials.join(", ")
    end
  end
end

app/views/units/_form.html.erb
<%= simple_form_for(@unit, wrapper: "form") do |f| %>
  <%= f.error_notification %>
  <div class="container-fluid">
    <div class="form-wizard-basic fw-container">
      <div class="tab-content">
        <div class="tab-pane fade active in" id="step-1">
          <div class="row-fluid">
            <div class="row">
              <div class="col-md-12">
                <%= f.input :name, disabled: true %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <%= f.input :min_age, collection: 12..22 %>
              </div>
              <div class="col-md-6">
                <%= f.input :max_age, collection: 12..22 %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <%= f.association :measure_types, input_html: { class: "select2 big-select2" }%>
              </div>
            </div>

            <div class="row">
              <div class="col-md-4">
                <%= f.input :street %>
              </div>

              <div class="col-md-4">
                <%= f.input :district %>
              </div>

              <div class="col-md-4">
                <%= f.input :county %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <%= f.input :latitude %>
              </div>
              <div class="col-md-6">
                <%= f.input :longitude %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <%= f.file_field :photo %>
                <%= f.hidden_field :photo_cache %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row form-actions">
    <hr>
    <div class="col-md-12">
      <%= footer_actions(units_path) %>
    </div>
  </div>
<% end %>
</div>

app/views/units/_infowindow.html.erb
<span class="content-modal">
  <div class="modal-body">
    <table class="table table-stripped">
      <thead>
        <tr>
          <th colspan="4" class="text-center"><%= unit.name %></th>
        </tr>
      </thead>
      <tbody>
        <%= image_tag(unit.photo_url, size: "450x200") if unit.photo? %>

        <tr>
          <td>
            <b><%= t("activerecord.attributes.unit.min_age") %>:</b>
          </td>
          <td>
            <%= unit.min_age %>
          </td>

          <td>
            <b><%= t("activerecord.attributes.unit.max_age") %>:</b>
          </td>
          <td>
            <%= unit.max_age %>
          </td>
        </tr>
        <tr>
          <td >
            <b><%= t("activerecord.attributes.unit.measure_types") %>:</b>
          </td>
          <td colspan='3' >
            <%= unit.measure_types_names %>
          </td>
        </tr>
        <tr>
          <td>
            <b><%= t("activerecord.attributes.unit.capacity") %>:</b>
          </td>
          <td>
            <%= unit.capacity %>
          </td>

          <td>
            <b><%= t("views.maps.unit_occupation") %>:</b>
          </td>
          <td>
            <%= unit.offenders.not_evaded.count %>
          </td>
        </tr>
        <tr>
          <td>
            <b><%= t("views.maps.total_on_age") %>:</b>
          </td>
          <td>
            <%= unit.offenders_out_of_profile_by_age %>
          </td>

          <td>
            <b><%= t("views.maps.total_on_measure") %>:</b>
          </td>
          <td>
            <%= unit.offenders_out_of_measure %>
          </td>
        </tr>
        <tr>
          <td>
            <b><%= t("views.maps.evaded") %>:</b>
          </td>
          <td>
            <%= unit.offenders.evaded.count %>
          </td>

          <td>
            <b><%= t("views.maps.inconsistences") %>:</b>
          </td>
          <td>
            <%= unit.inconsistences %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</span>

app/views/units/edit.html.erb
<div class="tile">
  <div class="t-header">
  </div>
  <div class="t-body">
    <%= render 'form' %>
  </div>
</div>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container overflow-visible">
  <div class="tile">
    <div class="t-header th-alt bg-teal">
      <div class="th-title">
        <span class="tile-text"><%= t("views.units.list_units")%></span>
      </div>
    </div>
    <table class="table table-stripped">
      <thead>
        <tr>
          <th><%= t("activerecord.attributes.unit.name") %></th>
          <th><%= t("activerecord.attributes.unit.min_age") %></th>
          <th><%= t("activerecord.attributes.unit.max_age") %></th>
          <th><%= t("activerecord.attributes.unit.created_at") %></th>
          <th><%= t("activerecord.attributes.unit.updated_at") %></th>
          <th><%= t("activerecord.attributes.unit.measure_types") %></th>
          <th><%= t("views.general.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @units.each do |unit| %>
        <tr>
          <td><%= unit.name %></td>
          <td><%= unit.min_age %></td>
          <td><%= unit.max_age %></td>
          <td><%= l(unit.created_at, format: :short) %></td>
          <td><%= l(unit.updated_at, format: :short) %></td>
          <td><%= unit.measure_types.map(&:name) %></td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-success dropdown-toggle"  data-toggle="dropdown" aria-expanded="false">
                <%= fa_icon("ellipsis-h") %>
              </button>
              <ul class="dropdown-menu dropdown-menu-right" data-placement="left" role="menu">
                <li>
                <%= link_to edit_unit_path(unit), data: { link: edit_unit_path(unit) } do %>
                  <%= fa_icon("pencil-square-o") %>
                  <%= t("link.edit") %>
                <% end %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>
<%= render partial: "layouts/skinny_modal" %>

app/views/units/show.html.erb
<span class="content-modal">
  <div class="modal-body">
    <table class="table table-stripped">
      <thead class="bg-teal">
        <tr>
          <th colspan="4" class="text-center"><%= @unit.name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <b><%= t("activerecord.attributes.activity.name_responsible") %>:</b>
          </td>
          <td>
            <%= @unit.min_age %>
          </td>

          <td>
            <b><%= t("activerecord.attributes.activity.user_id") %>:</b>
          </td>
          <td>
            <%= @unit.max_age %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="modal-footer">
    <hr>
    <%= link_to "", class: "btn btn-danger btn-icon", id: "btn-close-modal", data: { dismiss: "modal" } do %>
      <%= fa_icon("close") %>
    <% end %>
  </div>
</span>